---
sudo: false
language: go

env:
  global:
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=1
    - DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_REPO
    - BUILD_TAG="${TRAVIS_TAG:-untagged}-$(date +%s)"
  matrix:
    - CC=gcc CXX=gcc
    - CC=musl-gcc CXX=musl-gcc DOCKER_ENABLED=1

before_install:
  - test $CC != musl-gcc || sudo apt-get install musl-tools

install:
  - go get -v -d -t ./...

script:
  - go vet *.go
  - test $CC = musl-gcc || go test -v -race -cover ./...
  - go build -v -a -o mailhook .
  - test ! $DOCKER_ENABLED || docker build --pull --no-cache -t $DOCKER_IMAGE .

before_deploy:
  - REAL_GO_VERSION=$(go version | cut -d' ' -f3)
  - if [[ $DOCKER_ENABLED ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY;
      docker tag $DOCKER_IMAGE ${DOCKER_IMAGE}:${BUILD_TAG}-${REAL_GO_VERSION};
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push ${DOCKER_IMAGE}:${BUILD_TAG}-${REAL_GO_VERSION};
    on:
      branch: feature/dockerize
      # tags: true
      condition: $DOCKER_ENABLED
